### ISSUE TITLE
Allow developers to access Product resource

### ISSUE THREAD

**Issue by stevebrownlee** [Phat-Taupe-Pests/BangazonAPI#2]
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list of products, and GET a single product.

**Comment by chazhenricks** [comment]
Uncomment ProducttypeID and CustomerID 

Also add more documentation for Model/Product.cs and Controllers/ProductController.cs
Need info on what each of the methods do. 
[Definition Of Done](https://github.com/nashville-software-school/bangazon-inc/blob/master/EMPLOYEE_HANDBOOK.md#definition-of-done)
