### ISSUE TITLE
Allow developers to access the Payment Type resource

### ISSUE THREAD

**Issue by stevebrownlee** [Phat-Taupe-Pests/BangazonAPI#3]
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list, and GET a single item.

**Comment by chazhenricks** [comment]
Still needs better documentation in 
Models/ProductType.cs and
Controllers/ProductTypeController.cs

Specifically in defining what each class/method do. 

[Definition Of Done](https://github.com/nashville-software-school/bangazon-inc/blob/master/EMPLOYEE_HANDBOOK.md#definition-of-done)
